[deploy_website] integrated guild-docs as website (#3085)
API routes generation fix

docs & components update; routing fixes

gitignore update

fix(deps): update dependency extract-files to v11 (#3065)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(deps): update dependency tslib to ~2.3.0 (#3067)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(deps): update dependency the-guild-components to v1.3.1 (#3070)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(deps): update dependency apollo-upload-client to v16 (#3066)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update typescript-eslint monorepo to v4.27.0 (#3071)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update babel monorepo to v7.14.6 (#3072)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

[deploy_website] Update generate-schema.md (#3074)

corrected grammar

fix(deps): update dependency globby to v11.0.4 (#3077)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(deps): update dependency ws to v7.5.0 (#3078)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency typescript to v4.3.3 (#3083)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency typedoc to v0.20.37 (#3082)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

Jest Transformer for GraphQL (#1887)

* Jest Transformer for GraphQL

* Changeset

* Align versions

* Fix package.json

* yarn.lock

* Fix

Co-authored-by: Arda TANRIKULU <ardatanrikulu@gmail.com>

chore(deps): update dependency @types/ws to v7.4.5 (#3084)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

Safer use of `Object.prototype.hasOwnProperty` (#3069)

* Safer use of `Object.prototype.hasOwnProperty`

Fixes an error I get when GraphQL JS passes a prototypeless object into the resolver

```
ReferenceError: maybeRef is not defined
    at eval (eval at <anonymous> (/Users/mattalexander/Projects/edge-sites-schema/tests/regression.test.js:67:7), <anonymous>:1:38)
    at forEach (/projectpath/tests/regression.test.js:67:7)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/projectpath/tests/regression.test.js:65:17)
```

* changeset and test

Co-authored-by: Arda TANRIKULU <ardatanrikulu@gmail.com>

BugFix: Handle parsing endpoints when there are no mutations (#3076)

* BugFix: Handle parsing endpoints when there are no mutations

* changeset and test

* pass tests

Co-authored-by: itai <itaimain@gmail.com>
Co-authored-by: Arda TANRIKULU <ardatanrikulu@gmail.com>

chore(deps): update dependency typescript to v4.3.4 (#3086)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency typedoc to v0.21.0 (#3087)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency typedoc-plugin-markdown to v3.10.0 (#3088)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency eslint to v7.29.0 (#3089)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency graphql to v15.5.1 (#3091)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

enable typescript strict mode (#3010)

* enable noImplicitThis

* enable `strictBindCallApply`

* enable `strictFunctionTypes` 1: testing

* enable `strictFunctionTypes` 2: utils

* enable strictFunctionTypes 3: schema

* enable strictFunctionTypes 4: batch-execute

* enable strictFunctionTypes 5 `load`

* enable strictFunctionTypes 6 `loaders/url`

* enable strictFunctionTypes 7 `webpack-loader`

* enable strictFunctionTypes 8 `links`

* enable strictFunctionTypes 9 `delegate` and `batch-delegate`

* enable `strictFunctionTypes` 10 `wrap`

* enable `strictFunctionTypes` 11 `stitch` and `stitching-directive`

* enable `strictFunctionTypes` final tsconfig

* remove unnecessary generic params

* enable `strictNullChecks` 1 `utils`

* enable `strictNullChecks` 2 `schema`

* enable `strictNullChecks` 3 `resolvers-composition`

* enable `strictNullChecks` 4 `webpack-loader`

* enable `strictNullChecks` 5 `batch-execute`

* enable `strictNullChecks` 6 `graphql-tag-plug`

* enable `strictNullChecks` 7 `import`

* enable `strictNullChecks` 8 `loaders/url`

* enable `strictNullChecks` 8 `loaders/prisma`

* enable `strictNullChecks` 8 `loaders/module`

* enable `strictNullChecks` 9 `loaders/github`

* enable `strictNullChecks` 12 `loaders/code-file`

* enable `strictNullChecks` 13 `load`

* enable `strictNullChecks` 14 `delegate`

* enable `strictNullChecks` 15 `batch-delegate`

* interlude: move commonly used stuff to testing folder

* enable `strictNullChecks` 16 `wrap`

* enable `strictNullChecks` 17 `stitch`

* enable `strictNullChecks` 18 `load-files`

* enable `strictNullChecks` 19 `load-typedefs`

* enable `strictNullChecks` 20 `merge`

* enable `strictNullChecks` 21 `node-require`

* enable `strictNullChecks` 22 `mock`

* enable `strictNullChecks` 22 `stitching-directive`

* enable `strictNullChecks` flag in tsconfig

* fix: graphql-js 14 compat

* fix `strictPropertyInitialization` errors

* enable strictPropertyInitialization rule

* strict mode!!!

* enable `noPropertyAccessFromIndexSignature`

* enable `noFallthroughCasesInSwitch` and `noPropertyAccessFromIndexSignature`

* Add strict to new changes

* fix: remove casts as upstream issue is fixed

* fix: throw if we cannot identify the operation type.

https://github.com/ardatan/graphql-tools/pull/3010#discussion_r647348250
https://github.com/ardatan/graphql-tools/pull/3010#discussion_r647348389

* fix: change wording of error

https://github.com/ardatan/graphql-tools/pull/3010#discussion_r647350844

* fix: make error message more clear

https://github.com/ardatan/graphql-tools/pull/3010#discussion_r647354463

* refactor: use null/undefined instead of falsey check

* fix: assert operation from document

https://github.com/ardatan/graphql-tools/pull/3010#discussion_r647371024

* fix: type narrowing not working due to generics

https://github.com/ardatan/graphql-tools/pull/3010#discussion_r647373272

* fix: apply feedback for relocateError

* Make wrapSchema generic. Fix #3064 (#1)

* Fix Build

Co-authored-by: Arda TANRIKULU <ardatanrikulu@gmail.com>
Co-authored-by: Augustin Le Fèvre <augustin.public@gmail.com>

Huge cleanup before major release (breaking) (#3081)

* Breaking cleanup before major release

* Fix TS

* More

chore(deps): update typescript-eslint monorepo to v4.28.0 (#3093)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(deps): update babel monorepo to v7.14.7 (#3094)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update jest monorepo to v27.0.5 (#3095)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency @vue/compiler-sfc to v3.1.2 (#3097)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix build errors

Huge cleanup before major release (breaking) (#3081)

* Breaking cleanup before major release

* Fix TS

* More

chore(deps): update typescript-eslint monorepo to v4.28.0 (#3093)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(deps): update babel monorepo to v7.14.7 (#3094)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update jest monorepo to v27.0.5 (#3095)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency @vue/compiler-sfc to v3.1.2 (#3097)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(deps): update dependency the-guild-components to v1.4.0 (#3098)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency @types/node to v14.17.4 (#3101)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

Some other refactor (#3096)

* Fix typing errors in tests

* ReplaObject.keys/values and forEach with for..in and for..of loops

* Improve Type Checking

* Update CI workflow

* Fix linting

* Fix TS errors for v14

* More

* More

* Allow incremental builds

* Finish

* Fix Type Check

* Disable sourcemaps

* Fix type issues

Better changelog

Respect  and  in  and more changes

chore(CI): Ability to release canaries on demand

Make AggregateError spec compliant

reintegration

docs update

updated tgc version and removed Poppins import

Able to release with custom tags

chore(deps): update dependency typedoc-plugin-markdown to v3.10.2 (#3107)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

Prevent TS Server to die on VSCode

chore(deps): update dependency typedoc to v0.21.1 (#3108)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency graphql-tag to v2.12.5 (#3109)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency prettier to v2.3.2 (#3110)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency typedoc to v0.21.2 (#3111)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency @types/babel__traverse to v7.14.0 (#3112)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update jest monorepo to v27.0.6 (#3115)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

Remove Subscriber and use only Executor (#3117)

* Remove Subscriber and use only Executor

* Fix introspectSchema

* Fix tests

* Cleanup

fix(deps): update dependency ws to v7.5.1 (#3118)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

enhance(url-loader): refactor

Fix rawSDL issue

enhance(delegate): skip validation by default and add validateRequest option to enable

chore(deps): update dependency typescript to v4.3.5 (#3122)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(file-loader): location path must be normalized (#3121)

chore(deps): update dependency husky to v7 (#3123)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

feat(graphql-tag-pluck): keep locationOffset and return graphql-js Source instead of string

chore(deps): update dependency @vue/compiler-sfc to v3.1.3 (#3125)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency @vue/compiler-sfc to v3.1.4 (#3126)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(deps): update dependency @types/websocket to v1.0.3 (#3129)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency @types/ws to v7.4.6 (#3128)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency eslint to v7.30.0 (#3130)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(deps): update dependency ws to v7.5.2 (#3131)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

fix(url-loader): fix node support for EventSource

feat(resolvers-composition): add support for glob patterns (#3132)

* feat(resolvers-composition): add support for glob patterns

* fix(resolvers-composition): add typings for micromatch

* feat(resolvers-composition): add unit tests for glob patterns

* chore(resolver-compositions): cleanup

* feat(docs): added samples for resolver composition path matcher format

* chore: added changeset

* fix(docs): typo

* fix(changeset): change patch to minor

* Fix tests and cleanup

Co-authored-by: Arda TANRIKULU <ardatanrikulu@gmail.com>

chore(deps): pin dependency @types/micromatch to 4.0.1 (#3133)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

chore(deps): update dependency nock to v13.1.1 (#3134)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

don't throw on errors that should not be relocated (#3136)

refactor: internal StitchingInfo properties (#3137)

to never be undefined

docs update

docs update after review

Some fixes

update tgc version